name: ProductMap Map Requirement Alignment
description: |
  Generates a AI key features map, requirement analysis result via ProductMap tool, and retrieves generated map URLs.

branding:
  icon: "share-2"
  color: "blue"

inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  user_email:
    description: 'User email'
    required: false

permissions:
  contents: write
  pull-requests: write

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures full commit history is fetched

    - name: Check repository visibility
      shell: bash
      run: |
        if [ "${{ github.event.repository.private }}" = "true" ]; then
          echo "This is a private repository. The extension only works for public repositories."
          exit 1
        else
          echo "This is a public repository."
        fi

    - name: Check if PR is from a fork
      id: check_fork
      shell: bash
      run: |
        if [[ "${{ github.event.pull_request.head.repo.fork }}" == "true" ]]; then
          echo "This PR is coming from a fork. Skipping branch push and PR creation."
          echo "IS_FORK=true" >> $GITHUB_ENV
        else
          echo "This PR is from the main repository"
          echo "IS_FORK=false" >> $GITHUB_ENV
        fi

    - name: Get GitHub User Info
      id: user-info
      shell: bash
      run: |
        # Fetch user info from the GitHub API
        {
          USER_JSON=$(curl -s -H "Authorization: token ${{ inputs.github_token }}" \
            -w "%{http_code}" \
            https://api.github.com/users/${GITHUB_ACTOR})

          # Extract HTTP status code (last 3 digits of USER_JSON)
          HTTP_STATUS="${USER_JSON: -3}"
          USER_JSON="${USER_JSON::-3}"  # Remove last 3 digits (HTTP code) to keep only JSON

          
          # Check if the API request was successful
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Failed to fetch user info. HTTP Status: $HTTP_STATUS"
            echo "API Response: $USER_JSON"
          else
           echo "User info fetched successfully"
          fi
          
          # Verify that the response is valid JSON
          if ! echo "$USER_JSON" | jq empty > /dev/null 2>&1; then
            echo "Error: Invalid JSON response from GitHub API"
            echo "Response received: $USER_JSON"
            exit 1
          fi
        
          # Extract username and email from API response stored in USER_JSON
          NICKNAME=$(echo "$USER_JSON" | jq -r '.login')
          PUBLIC_EMAIL=$(echo "$USER_JSON" | jq -r '.email')
        
          # Assign a default nickname if empty
          if [ -z "$NICKNAME" ] || [ "$NICKNAME" == "null" ]; then
            NICKNAME="public-user"
          fi
        
        } || {
          echo "Failed to fetch user info from GitHub API"
          echo "Using default email and username"
          NICKNAME="null"
          PUBLIC_EMAIL="null"
        }
  
        # Handle if the email is null (public email not set)
        if [ "$PUBLIC_EMAIL" == "null" ]; then
          echo "No public email available from GitHub API"
          PUBLIC_EMAIL="No public email available"
        fi

        # Check if email is available from environment variable
        if [ "$PUBLIC_EMAIL" == "No public email available" ] && [ ! -z "${{ inputs.user_email }}" ]; then
          PUBLIC_EMAIL="${{ inputs.user_email }}"
        fi

        # Check if email is available from the most recent commit
        if [ "$PUBLIC_EMAIL" == "No public email available" ]; then
          echo "Trying to get email from the most recent commit"
          COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
          PUBLIC_EMAIL=$COMMIT_EMAIL
        fi
        
        # Print the obtained email for debugging
        echo "Final email: $PUBLIC_EMAIL"
        echo "Final nickname: $NICKNAME"
        
        # Evaluate if the email is still not available
        if [ "$PUBLIC_EMAIL" == "No public email available" ]; then
          echo "No public email available"
          PUBLIC_EMAIL="null"
          NICKNAME="null"
        fi
        
        # Save to environment variables
        echo "NICKNAME=$NICKNAME" >> $GITHUB_ENV
        echo "PUBLIC_EMAIL=$PUBLIC_EMAIL" >> $GITHUB_ENV


    - name: Install ProductMap CLI
      shell: bash
      run: |
        echo "Installing ProductMap CLI"
        pip install productmap-cli

    - name: Generate and get requirements alignment results for repository
      shell: bash
      run: |
        # Detect if the repository is a fork and process files accordingly
        REPO_URL="https://github.com/${{ github.repository }}"
        BRANCH_NAME="${GITHUB_REF_NAME}"
        
        echo "Processing files from repository: $REPO_URL on branch: $BRANCH_NAME"
        # Send file to create a generated map and get the requirement analysis result
        echo "Send file to create a generated map and get the requirement analysis result"
        pm-cli "$REPO_URL" "$NICKNAME" "$PUBLIC_EMAIL" --action="analyze_requirements" > response.json
        EXIT_CODE=$?
        if [ $EXIT_CODE -ne 0 ]; then
            echo "pm-cli failed with exit code $EXIT_CODE." >&2
            cat response.json
            exit $EXIT_CODE
        fi
          echo "Response from pm-cli:"
          cat response.json
        
          # Append the response to the combined output
          RESPONSE=$(tail -n 1 response.json)
        
          echo "Response from pm-cli:"
          echo "$RESPONSE"
        done

    - name: Verify if folder alignment_results exists
      shell: bash
      run: |
        if [ ! -d "alignment_results" ]; then
          echo "Creating alignment_results directory"
          mkdir alignment_results
        else
          echo "alignment_results directory already exists"
        fi

    - name: Create markdown file with results
      shell: bash
      run: |
        # Access alignment_results directory
        cd alignment_results || exit 1
        echo "Current directory: $(pwd)"
        echo "Contents of alignment_results directory:"
        ls -la
        echo "Creating markdown file with results"
        
        # Debug: Show environment info
        echo "::group::Debug Info"
        echo "PWD: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "::endgroup::"
        
        # Define constants
        PRODUCT_MAP_LOGO_URL="https://product-map.ai/product_map_logo.png"
        PRODUCT_MAP_HOME_URL="https://product-map.ai"
        CONTACT_US_URL="https://product-map.ai"

        # Validate JSON file exists
        if [ ! -f "response.json" ]; then
          echo "❌ Error: response.json not found!" >&2
          exit 1
        fi

        # Validate jq is installed
        if ! command -v jq &> /dev/null; then
          echo "❌ Error: jq not installed!" >&2
          exit 1
        fi

        # Validate JSON syntax
        if ! jq empty response.json; then
          echo "❌ Invalid JSON in response.json!" >&2
          exit 1
        fi

        echo "::group::JSON Content"
        cat response.json
        echo "::endgroup::"

        # Create markdown with error handling
        set -euo pipefail  # Enable strict mode

        FILENAME_DATE=$(date +'%H:%M:%S_%d%m%y')
        CONTENT_DATE=$(date +'%Y-%m-%d %H:%M:%S')
        MD_FILENAME="requirement_analysis_results_${FILENAME_DATE}.md"

        echo "ℹ️ Starting markdown generation..." >&2

        # Header with image
        echo "# ProductMap Requirement Alignment Results" > "$MD_FILENAME"
        echo "" >> "$MD_FILENAME"
        echo "<p align=\"center\"><a href=\"$PRODUCT_MAP_HOME_URL\" target=\"_blank\"><img src=\"$PRODUCT_MAP_LOGO_URL\" width=\"50%\"></a></p>\n" >> "$MD_FILENAME"
        echo "" >> "$MD_FILENAME"
        echo "**Creation Date:** $CONTENT_DATE" >> "$MD_FILENAME"
        echo "" >> "$MD_FILENAME"
        echo "## Analysis Results" >> "$MD_FILENAME"
        echo "" >> "$MD_FILENAME"

        # Table
        echo "| Feature ID | Feature Description | Key Criteria | Status | Notes |" >> "$MD_FILENAME"
        echo "|-----------|---------------------|--------------|--------|-------|" >> "$MD_FILENAME"

        # Process JSON
        echo "ℹ️ Processing JSON data..." >&2
        jq -c '.[]' response.json | while read -r item; do
          echo "Processing item: $item" >&2
          
          FEATURE_ID=$(echo "$item" | jq -r '.feature_id // empty')
          FEATURE_DESC=$(echo "$item" | jq -r '.feature_description // empty')
          KEY_CRITERIA=$(echo "$item" | jq -r '.key_criteria // empty')
          STATUS=$(echo "$item" | jq -r '.status // empty')
          NOTES=$(echo "$item" | jq -r '.notes // empty')

          # Validate required fields
          if [ -z "$FEATURE_ID" ]; then
            echo "❌ Missing feature_id in item: $item" >&2
            exit 1
          fi

          echo "| $FEATURE_ID | $FEATURE_DESC | $KEY_CRITERIA | $STATUS | $NOTES |" >> "$MD_FILENAME"
        done

        echo "✅ Markdown file created: $MD_FILENAME" >&2
        echo "::group::Generated Markdown"
        cat "$MD_FILENAME"
        echo "::endgroup::"


    - name: Set up Git
      shell: bash
      if: env.IS_FORK == 'false'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Generate dynamic branch name
      shell: bash
      if: env.IS_FORK == 'false'
      id: generate_branch_name
      run: |
        # Generate branch name based on timestamp
        BRANCH_NAME="pm-requirement-alignment-$(date +'%Y%m%d%H%M%S')"  # Format: pm-YYYYMMDDHHMMSS
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "Generated branch name: ${BRANCH_NAME}"

    - name: Create a new branch
      shell: bash
      if: env.IS_FORK == 'false'
      run: |
        git checkout -b ${{ env.BRANCH_NAME }}  # Use the dynamically generated branch name

    - name: Make changes to the repository
      shell: bash
      if: env.IS_FORK == 'false'
      run: |
        echo "Add requirement alignment result" > newfile.txt
        git add alignment_results/requirement_analysis_results_*.md

    - name: Commit changes
      shell: bash
      if: env.IS_FORK == 'false'
      run: |
        git commit -m "ProductMap requirement alignment result" || echo "No changes to commit"

    - name: Push the new branch and commit
      shell: bash
      if: env.IS_FORK == 'false'
      run: |
        git push --set-upstream origin ${{ env.BRANCH_NAME }}  # Push to the newly created branch and set upstream

    - name: Create a pull request
      shell: bash
      if: env.IS_FORK == 'false'
      run: |
        # Create the PR using the GitHub API
        curl -X POST \
          -H "Authorization: token ${{ inputs.github_token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{
                "title": "Auto-generated PR for branch '${{ inputs.branch_name }}'",
                "head": "'${{ env.BRANCH_NAME }}'",
                "base": "${{ inputs.target_branch }}",
                "body": "This pull request was created automatically by GitHub Actions to merge the changes from '${{ inputs.branch_name }}' into the main branch."
              }'


